color:
  B:
    L_S: 41
    L_V: 29
    U_S: 255
    U_V: 255
    centre: 108
    error: 12
  G:
    L_S: 41
    L_V: 29
    U_S: 255
    U_V: 255
    centre: 69
    error: 12
  R:
    L_S: 41
    L_V: 29
    U_S: 255
    U_V: 255
    centre: 0
    error: 12
color_ring:
  alpha: 4.4
  clahe_clip_limit: 0.8
  clahe_tile_size: 8
  dilate_kernel_size: 5
  erode_iter: 1
  expected_circles: 5
  gaussian_kernel_size: 9
  gaussian_sigma: 1.5
  hough_dp: 0.9
  hough_min_dist: 68
  hough_param1: 72
  hough_param2: 100
  max_radius: 281
  min_radius: 54
  morph_kernel_size: 3
  threshold_value: 69
max_material_area: 300000
min_material_area: 5940
need2cut_height: 0
target_angle: 46
